FROM ivs0/b-ros

RUN apt-get update && apt-get install -y git software-properties-common \
        && add-apt-repository ppa:george-edison55/cmake-3.x && apt-get update \
	&& apt-get install -y zip make cmake gcc g++
